### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by FormSans** [BLKNeko/LC-HookGun#1]
I have the Reserve slot mod and I was wondering if you would ever think to add a compatibility so the hookgun can have its own reserved slot?

**Comment by BLKNeko** [comment]
> I have the Reserve slot mod and I was wondering if you would ever think to add a compatibility so the hookgun can have its own reserved slot?

Oh well, i never tried, i will take a look when i have some time!

**Comment by BLKNeko** [comment]
Hey, about the reserved slot, I did it, sorry for the delayed update.
