### ISSUE TITLE
API problem?

### ISSUE THREAD

**Issue by FormSans** [BLKNeko/LC-HookGun#2]
Recently tried to play while the API was activated, but it wouldn't let me land the ship. Seemed broken as I disabled it and I could land the ship again.

**Comment by Kori101** [comment]
The original 2018 LC API isn't maintained anymore but there has been a repacked version that seems to work so far as of posting this. 

Mod Info here : https://thunderstore.io/c/lethal-company/p/DrFeederino/LC_API_V50/

**Comment by BLKNeko** [comment]
Ohh i see, didn`t updated the project for quiete a long time...
I will take a look and maybe update it...

**Comment by BLKNeko** [comment]
I managed to review and test the new update, and it seems there’s no longer a need for the LC API. I’ve removed the dependency, and it now appears to be working quite well.

**Comment by Kori101** [comment]
Thank you for your response and work :)
